/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestTermsRouteImport } from './routes/_guest/terms'
import { Route as GuestPrivacyRouteImport } from './routes/_guest/privacy'
import { Route as GuestFaqRouteImport } from './routes/_guest/faq'
import { Route as GuestContactRouteImport } from './routes/_guest/contact'
import { Route as GuestCheckoutRouteImport } from './routes/_guest/checkout'
import { Route as GuestCartRouteImport } from './routes/_guest/cart'
import { Route as GuestAboutRouteImport } from './routes/_guest/about'
import { Route as GuestEventsIndexRouteImport } from './routes/_guest/events/index'
import { Route as GuestActivitiesIndexRouteImport } from './routes/_guest/activities/index'
import { Route as GuestAccountIndexRouteImport } from './routes/_guest/account/index'
import { Route as GuestAccommodationsIndexRouteImport } from './routes/_guest/accommodations/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as GuestEventsSlugRouteImport } from './routes/_guest/events/$slug'
import { Route as GuestConfirmationIdRouteImport } from './routes/_guest/confirmation/$id'
import { Route as GuestAuthResetPasswordRouteImport } from './routes/_guest/auth/reset-password'
import { Route as GuestAuthRegisterRouteImport } from './routes/_guest/auth/register'
import { Route as GuestAuthLoginRouteImport } from './routes/_guest/auth/login'
import { Route as GuestAuthForgotPasswordRouteImport } from './routes/_guest/auth/forgot-password'
import { Route as GuestActivitiesSlugRouteImport } from './routes/_guest/activities/$slug'
import { Route as GuestAccountProfileRouteImport } from './routes/_guest/account/profile'
import { Route as GuestAccountFavoritesRouteImport } from './routes/_guest/account/favorites'
import { Route as GuestAccountBookingsRouteImport } from './routes/_guest/account/bookings'
import { Route as GuestAccommodationsSlugRouteImport } from './routes/_guest/accommodations/$slug'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin/reports'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin/admin/bookings'
import { Route as AdminAdminActivitiesRouteImport } from './routes/_admin/admin/activities'
import { Route as AdminAdminAccommodationsIndexRouteImport } from './routes/_admin/admin/accommodations/index'
import { Route as AdminAdminAccommodationsCreateRouteImport } from './routes/_admin/admin/accommodations/create'
import { Route as AdminAdminAccommodationsViewIdRouteImport } from './routes/_admin/admin/accommodations/view/$id'
import { Route as AdminAdminAccommodationsEditIdRouteImport } from './routes/_admin/admin/accommodations/edit/$id'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestTermsRoute = GuestTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPrivacyRoute = GuestPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => GuestRoute,
} as any)
const GuestFaqRoute = GuestFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => GuestRoute,
} as any)
const GuestContactRoute = GuestContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => GuestRoute,
} as any)
const GuestCheckoutRoute = GuestCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => GuestRoute,
} as any)
const GuestCartRoute = GuestCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAboutRoute = GuestAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestRoute,
} as any)
const GuestEventsIndexRoute = GuestEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestActivitiesIndexRoute = GuestActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccountIndexRoute = GuestAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccommodationsIndexRoute =
  GuestAccommodationsIndexRouteImport.update({
    id: '/accommodations/',
    path: '/accommodations/',
    getParentRoute: () => GuestRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const GuestEventsSlugRoute = GuestEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => GuestRoute,
} as any)
const GuestConfirmationIdRoute = GuestConfirmationIdRouteImport.update({
  id: '/confirmation/$id',
  path: '/confirmation/$id',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAuthResetPasswordRoute = GuestAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAuthRegisterRoute = GuestAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAuthLoginRoute = GuestAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAuthForgotPasswordRoute = GuestAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestActivitiesSlugRoute = GuestActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccountProfileRoute = GuestAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccountFavoritesRoute = GuestAccountFavoritesRouteImport.update({
  id: '/account/favorites',
  path: '/account/favorites',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccountBookingsRoute = GuestAccountBookingsRouteImport.update({
  id: '/account/bookings',
  path: '/account/bookings',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAccommodationsSlugRoute = GuestAccommodationsSlugRouteImport.update({
  id: '/accommodations/$slug',
  path: '/accommodations/$slug',
  getParentRoute: () => GuestRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminActivitiesRoute = AdminAdminActivitiesRouteImport.update({
  id: '/admin/activities',
  path: '/admin/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAccommodationsIndexRoute =
  AdminAdminAccommodationsIndexRouteImport.update({
    id: '/admin/accommodations/',
    path: '/admin/accommodations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccommodationsCreateRoute =
  AdminAdminAccommodationsCreateRouteImport.update({
    id: '/admin/accommodations/create',
    path: '/admin/accommodations/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccommodationsViewIdRoute =
  AdminAdminAccommodationsViewIdRouteImport.update({
    id: '/admin/accommodations/view/$id',
    path: '/admin/accommodations/view/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccommodationsEditIdRoute =
  AdminAdminAccommodationsEditIdRouteImport.update({
    id: '/admin/accommodations/edit/$id',
    path: '/admin/accommodations/edit/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof GuestAboutRoute
  '/cart': typeof GuestCartRoute
  '/checkout': typeof GuestCheckoutRoute
  '/contact': typeof GuestContactRoute
  '/faq': typeof GuestFaqRoute
  '/privacy': typeof GuestPrivacyRoute
  '/terms': typeof GuestTermsRoute
  '/': typeof GuestIndexRoute
  '/admin/activities': typeof AdminAdminActivitiesRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/accommodations/$slug': typeof GuestAccommodationsSlugRoute
  '/account/bookings': typeof GuestAccountBookingsRoute
  '/account/favorites': typeof GuestAccountFavoritesRoute
  '/account/profile': typeof GuestAccountProfileRoute
  '/activities/$slug': typeof GuestActivitiesSlugRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordRoute
  '/auth/login': typeof GuestAuthLoginRoute
  '/auth/register': typeof GuestAuthRegisterRoute
  '/auth/reset-password': typeof GuestAuthResetPasswordRoute
  '/confirmation/$id': typeof GuestConfirmationIdRoute
  '/events/$slug': typeof GuestEventsSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/accommodations': typeof GuestAccommodationsIndexRoute
  '/account': typeof GuestAccountIndexRoute
  '/activities': typeof GuestActivitiesIndexRoute
  '/events': typeof GuestEventsIndexRoute
  '/admin/accommodations/create': typeof AdminAdminAccommodationsCreateRoute
  '/admin/accommodations': typeof AdminAdminAccommodationsIndexRoute
  '/admin/accommodations/edit/$id': typeof AdminAdminAccommodationsEditIdRoute
  '/admin/accommodations/view/$id': typeof AdminAdminAccommodationsViewIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof GuestAboutRoute
  '/cart': typeof GuestCartRoute
  '/checkout': typeof GuestCheckoutRoute
  '/contact': typeof GuestContactRoute
  '/faq': typeof GuestFaqRoute
  '/privacy': typeof GuestPrivacyRoute
  '/terms': typeof GuestTermsRoute
  '/': typeof GuestIndexRoute
  '/admin/activities': typeof AdminAdminActivitiesRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/accommodations/$slug': typeof GuestAccommodationsSlugRoute
  '/account/bookings': typeof GuestAccountBookingsRoute
  '/account/favorites': typeof GuestAccountFavoritesRoute
  '/account/profile': typeof GuestAccountProfileRoute
  '/activities/$slug': typeof GuestActivitiesSlugRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordRoute
  '/auth/login': typeof GuestAuthLoginRoute
  '/auth/register': typeof GuestAuthRegisterRoute
  '/auth/reset-password': typeof GuestAuthResetPasswordRoute
  '/confirmation/$id': typeof GuestConfirmationIdRoute
  '/events/$slug': typeof GuestEventsSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/accommodations': typeof GuestAccommodationsIndexRoute
  '/account': typeof GuestAccountIndexRoute
  '/activities': typeof GuestActivitiesIndexRoute
  '/events': typeof GuestEventsIndexRoute
  '/admin/accommodations/create': typeof AdminAdminAccommodationsCreateRoute
  '/admin/accommodations': typeof AdminAdminAccommodationsIndexRoute
  '/admin/accommodations/edit/$id': typeof AdminAdminAccommodationsEditIdRoute
  '/admin/accommodations/view/$id': typeof AdminAdminAccommodationsViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/about': typeof GuestAboutRoute
  '/_guest/cart': typeof GuestCartRoute
  '/_guest/checkout': typeof GuestCheckoutRoute
  '/_guest/contact': typeof GuestContactRoute
  '/_guest/faq': typeof GuestFaqRoute
  '/_guest/privacy': typeof GuestPrivacyRoute
  '/_guest/terms': typeof GuestTermsRoute
  '/_guest/': typeof GuestIndexRoute
  '/_admin/admin/activities': typeof AdminAdminActivitiesRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_guest/accommodations/$slug': typeof GuestAccommodationsSlugRoute
  '/_guest/account/bookings': typeof GuestAccountBookingsRoute
  '/_guest/account/favorites': typeof GuestAccountFavoritesRoute
  '/_guest/account/profile': typeof GuestAccountProfileRoute
  '/_guest/activities/$slug': typeof GuestActivitiesSlugRoute
  '/_guest/auth/forgot-password': typeof GuestAuthForgotPasswordRoute
  '/_guest/auth/login': typeof GuestAuthLoginRoute
  '/_guest/auth/register': typeof GuestAuthRegisterRoute
  '/_guest/auth/reset-password': typeof GuestAuthResetPasswordRoute
  '/_guest/confirmation/$id': typeof GuestConfirmationIdRoute
  '/_guest/events/$slug': typeof GuestEventsSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_guest/accommodations/': typeof GuestAccommodationsIndexRoute
  '/_guest/account/': typeof GuestAccountIndexRoute
  '/_guest/activities/': typeof GuestActivitiesIndexRoute
  '/_guest/events/': typeof GuestEventsIndexRoute
  '/_admin/admin/accommodations/create': typeof AdminAdminAccommodationsCreateRoute
  '/_admin/admin/accommodations/': typeof AdminAdminAccommodationsIndexRoute
  '/_admin/admin/accommodations/edit/$id': typeof AdminAdminAccommodationsEditIdRoute
  '/_admin/admin/accommodations/view/$id': typeof AdminAdminAccommodationsViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/users'
    | '/accommodations/$slug'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/profile'
    | '/activities/$slug'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/confirmation/$id'
    | '/events/$slug'
    | '/admin'
    | '/accommodations'
    | '/account'
    | '/activities'
    | '/events'
    | '/admin/accommodations/create'
    | '/admin/accommodations'
    | '/admin/accommodations/edit/$id'
    | '/admin/accommodations/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/users'
    | '/accommodations/$slug'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/profile'
    | '/activities/$slug'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/confirmation/$id'
    | '/events/$slug'
    | '/admin'
    | '/accommodations'
    | '/account'
    | '/activities'
    | '/events'
    | '/admin/accommodations/create'
    | '/admin/accommodations'
    | '/admin/accommodations/edit/$id'
    | '/admin/accommodations/view/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_guest'
    | '/_guest/about'
    | '/_guest/cart'
    | '/_guest/checkout'
    | '/_guest/contact'
    | '/_guest/faq'
    | '/_guest/privacy'
    | '/_guest/terms'
    | '/_guest/'
    | '/_admin/admin/activities'
    | '/_admin/admin/bookings'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/reports'
    | '/_admin/admin/users'
    | '/_guest/accommodations/$slug'
    | '/_guest/account/bookings'
    | '/_guest/account/favorites'
    | '/_guest/account/profile'
    | '/_guest/activities/$slug'
    | '/_guest/auth/forgot-password'
    | '/_guest/auth/login'
    | '/_guest/auth/register'
    | '/_guest/auth/reset-password'
    | '/_guest/confirmation/$id'
    | '/_guest/events/$slug'
    | '/_admin/admin/'
    | '/_guest/accommodations/'
    | '/_guest/account/'
    | '/_guest/activities/'
    | '/_guest/events/'
    | '/_admin/admin/accommodations/create'
    | '/_admin/admin/accommodations/'
    | '/_admin/admin/accommodations/edit/$id'
    | '/_admin/admin/accommodations/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/terms': {
      id: '/_guest/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof GuestTermsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/privacy': {
      id: '/_guest/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof GuestPrivacyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/faq': {
      id: '/_guest/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof GuestFaqRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/contact': {
      id: '/_guest/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof GuestContactRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/checkout': {
      id: '/_guest/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof GuestCheckoutRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/cart': {
      id: '/_guest/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof GuestCartRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/about': {
      id: '/_guest/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestAboutRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/events/': {
      id: '/_guest/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof GuestEventsIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/activities/': {
      id: '/_guest/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof GuestActivitiesIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/account/': {
      id: '/_guest/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof GuestAccountIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/accommodations/': {
      id: '/_guest/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof GuestAccommodationsIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_guest/events/$slug': {
      id: '/_guest/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof GuestEventsSlugRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/confirmation/$id': {
      id: '/_guest/confirmation/$id'
      path: '/confirmation/$id'
      fullPath: '/confirmation/$id'
      preLoaderRoute: typeof GuestConfirmationIdRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/auth/reset-password': {
      id: '/_guest/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof GuestAuthResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/auth/register': {
      id: '/_guest/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof GuestAuthRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/auth/login': {
      id: '/_guest/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/auth/forgot-password': {
      id: '/_guest/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof GuestAuthForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/activities/$slug': {
      id: '/_guest/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof GuestActivitiesSlugRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/account/profile': {
      id: '/_guest/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof GuestAccountProfileRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/account/favorites': {
      id: '/_guest/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof GuestAccountFavoritesRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/account/bookings': {
      id: '/_guest/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof GuestAccountBookingsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/accommodations/$slug': {
      id: '/_guest/accommodations/$slug'
      path: '/accommodations/$slug'
      fullPath: '/accommodations/$slug'
      preLoaderRoute: typeof GuestAccommodationsSlugRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/activities': {
      id: '/_admin/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminAdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accommodations/': {
      id: '/_admin/admin/accommodations/'
      path: '/admin/accommodations'
      fullPath: '/admin/accommodations'
      preLoaderRoute: typeof AdminAdminAccommodationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accommodations/create': {
      id: '/_admin/admin/accommodations/create'
      path: '/admin/accommodations/create'
      fullPath: '/admin/accommodations/create'
      preLoaderRoute: typeof AdminAdminAccommodationsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accommodations/view/$id': {
      id: '/_admin/admin/accommodations/view/$id'
      path: '/admin/accommodations/view/$id'
      fullPath: '/admin/accommodations/view/$id'
      preLoaderRoute: typeof AdminAdminAccommodationsViewIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/accommodations/edit/$id': {
      id: '/_admin/admin/accommodations/edit/$id'
      path: '/admin/accommodations/edit/$id'
      fullPath: '/admin/accommodations/edit/$id'
      preLoaderRoute: typeof AdminAdminAccommodationsEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminActivitiesRoute: typeof AdminAdminActivitiesRoute
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminAccommodationsCreateRoute: typeof AdminAdminAccommodationsCreateRoute
  AdminAdminAccommodationsIndexRoute: typeof AdminAdminAccommodationsIndexRoute
  AdminAdminAccommodationsEditIdRoute: typeof AdminAdminAccommodationsEditIdRoute
  AdminAdminAccommodationsViewIdRoute: typeof AdminAdminAccommodationsViewIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminActivitiesRoute: AdminAdminActivitiesRoute,
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminAccommodationsCreateRoute: AdminAdminAccommodationsCreateRoute,
  AdminAdminAccommodationsIndexRoute: AdminAdminAccommodationsIndexRoute,
  AdminAdminAccommodationsEditIdRoute: AdminAdminAccommodationsEditIdRoute,
  AdminAdminAccommodationsViewIdRoute: AdminAdminAccommodationsViewIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GuestRouteChildren {
  GuestAboutRoute: typeof GuestAboutRoute
  GuestCartRoute: typeof GuestCartRoute
  GuestCheckoutRoute: typeof GuestCheckoutRoute
  GuestContactRoute: typeof GuestContactRoute
  GuestFaqRoute: typeof GuestFaqRoute
  GuestPrivacyRoute: typeof GuestPrivacyRoute
  GuestTermsRoute: typeof GuestTermsRoute
  GuestIndexRoute: typeof GuestIndexRoute
  GuestAccommodationsSlugRoute: typeof GuestAccommodationsSlugRoute
  GuestAccountBookingsRoute: typeof GuestAccountBookingsRoute
  GuestAccountFavoritesRoute: typeof GuestAccountFavoritesRoute
  GuestAccountProfileRoute: typeof GuestAccountProfileRoute
  GuestActivitiesSlugRoute: typeof GuestActivitiesSlugRoute
  GuestAuthForgotPasswordRoute: typeof GuestAuthForgotPasswordRoute
  GuestAuthLoginRoute: typeof GuestAuthLoginRoute
  GuestAuthRegisterRoute: typeof GuestAuthRegisterRoute
  GuestAuthResetPasswordRoute: typeof GuestAuthResetPasswordRoute
  GuestConfirmationIdRoute: typeof GuestConfirmationIdRoute
  GuestEventsSlugRoute: typeof GuestEventsSlugRoute
  GuestAccommodationsIndexRoute: typeof GuestAccommodationsIndexRoute
  GuestAccountIndexRoute: typeof GuestAccountIndexRoute
  GuestActivitiesIndexRoute: typeof GuestActivitiesIndexRoute
  GuestEventsIndexRoute: typeof GuestEventsIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAboutRoute: GuestAboutRoute,
  GuestCartRoute: GuestCartRoute,
  GuestCheckoutRoute: GuestCheckoutRoute,
  GuestContactRoute: GuestContactRoute,
  GuestFaqRoute: GuestFaqRoute,
  GuestPrivacyRoute: GuestPrivacyRoute,
  GuestTermsRoute: GuestTermsRoute,
  GuestIndexRoute: GuestIndexRoute,
  GuestAccommodationsSlugRoute: GuestAccommodationsSlugRoute,
  GuestAccountBookingsRoute: GuestAccountBookingsRoute,
  GuestAccountFavoritesRoute: GuestAccountFavoritesRoute,
  GuestAccountProfileRoute: GuestAccountProfileRoute,
  GuestActivitiesSlugRoute: GuestActivitiesSlugRoute,
  GuestAuthForgotPasswordRoute: GuestAuthForgotPasswordRoute,
  GuestAuthLoginRoute: GuestAuthLoginRoute,
  GuestAuthRegisterRoute: GuestAuthRegisterRoute,
  GuestAuthResetPasswordRoute: GuestAuthResetPasswordRoute,
  GuestConfirmationIdRoute: GuestConfirmationIdRoute,
  GuestEventsSlugRoute: GuestEventsSlugRoute,
  GuestAccommodationsIndexRoute: GuestAccommodationsIndexRoute,
  GuestAccountIndexRoute: GuestAccountIndexRoute,
  GuestActivitiesIndexRoute: GuestActivitiesIndexRoute,
  GuestEventsIndexRoute: GuestEventsIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
