/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccommodationsIndexRouteImport } from './routes/accommodations/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as AdminAccommodationsRouteImport } from './routes/admin/accommodations'
import { Route as ActivitiesSlugRouteImport } from './routes/activities/$slug'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountFavoritesRouteImport } from './routes/account/favorites'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AccommodationsSlugRouteImport } from './routes/accommodations/$slug'
import { Route as BookingConfirmationIdRouteImport } from './routes/booking/confirmation/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsIndexRoute = AccommodationsIndexRouteImport.update({
  id: '/accommodations/',
  path: '/accommodations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/admin/activities',
  path: '/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccommodationsRoute = AdminAccommodationsRouteImport.update({
  id: '/admin/accommodations',
  path: '/admin/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/account/favorites',
  path: '/account/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsSlugRoute = AccommodationsSlugRouteImport.update({
  id: '/accommodations/$slug',
  path: '/accommodations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationIdRoute = BookingConfirmationIdRouteImport.update({
  id: '/booking/confirmation/$id',
  path: '/booking/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accommodations/$slug': typeof AccommodationsSlugRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/profile': typeof AccountProfileRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/accommodations': typeof AdminAccommodationsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/$slug': typeof EventsSlugRoute
  '/accommodations': typeof AccommodationsIndexRoute
  '/account': typeof AccountIndexRoute
  '/activities': typeof ActivitiesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/booking/confirmation/$id': typeof BookingConfirmationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accommodations/$slug': typeof AccommodationsSlugRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/profile': typeof AccountProfileRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/accommodations': typeof AdminAccommodationsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/$slug': typeof EventsSlugRoute
  '/accommodations': typeof AccommodationsIndexRoute
  '/account': typeof AccountIndexRoute
  '/activities': typeof ActivitiesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/booking/confirmation/$id': typeof BookingConfirmationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accommodations/$slug': typeof AccommodationsSlugRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/profile': typeof AccountProfileRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/accommodations': typeof AdminAccommodationsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/$slug': typeof EventsSlugRoute
  '/accommodations/': typeof AccommodationsIndexRoute
  '/account/': typeof AccountIndexRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/booking/confirmation/$id': typeof BookingConfirmationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/accommodations/$slug'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/profile'
    | '/activities/$slug'
    | '/admin/accommodations'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/events/$slug'
    | '/accommodations'
    | '/account'
    | '/activities'
    | '/admin'
    | '/events'
    | '/booking/confirmation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/accommodations/$slug'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/profile'
    | '/activities/$slug'
    | '/admin/accommodations'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/events/$slug'
    | '/accommodations'
    | '/account'
    | '/activities'
    | '/admin'
    | '/events'
    | '/booking/confirmation/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/accommodations/$slug'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/profile'
    | '/activities/$slug'
    | '/admin/accommodations'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/events/$slug'
    | '/accommodations/'
    | '/account/'
    | '/activities/'
    | '/admin/'
    | '/events/'
    | '/booking/confirmation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AccommodationsSlugRoute: typeof AccommodationsSlugRoute
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  AdminAccommodationsRoute: typeof AdminAccommodationsRoute
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EventsSlugRoute: typeof EventsSlugRoute
  AccommodationsIndexRoute: typeof AccommodationsIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  BookingConfirmationIdRoute: typeof BookingConfirmationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations/': {
      id: '/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accommodations': {
      id: '/admin/accommodations'
      path: '/admin/accommodations'
      fullPath: '/admin/accommodations'
      preLoaderRoute: typeof AdminAccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations/$slug': {
      id: '/accommodations/$slug'
      path: '/accommodations/$slug'
      fullPath: '/accommodations/$slug'
      preLoaderRoute: typeof AccommodationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation/$id': {
      id: '/booking/confirmation/$id'
      path: '/booking/confirmation/$id'
      fullPath: '/booking/confirmation/$id'
      preLoaderRoute: typeof BookingConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AccommodationsSlugRoute: AccommodationsSlugRoute,
  AccountBookingsRoute: AccountBookingsRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountProfileRoute: AccountProfileRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  AdminAccommodationsRoute: AdminAccommodationsRoute,
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EventsSlugRoute: EventsSlugRoute,
  AccommodationsIndexRoute: AccommodationsIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  BookingConfirmationIdRoute: BookingConfirmationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
